name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  post-build:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        if: ${{ failure() }}
        run: echo "Sending failure notification to agent"

      - name: Notify aborted
        if: ${{ cancelled() }}
        run: echo "Sending aborted notification to agent"

      - name: Notify success
        if: ${{ success() }}
        run: echo "Sending success notification to agent"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "Deploying to production..."
